### PR TITLE
Add art3mis to contributor byline

### PR DESCRIPTION
**Pull request by art3misxmoon**

### CODE REVIEW

**Review by FIGBERT — CHANGES_REQUESTED** [review]
I think having the commas at the beginning of the new lines is a little confusing. Could we maybe move them to the end of the previous line, after the tags, instead?

**Review by FIGBERT — CHANGES_REQUESTED** [review]
Is that a trailing space?

**Comment by art3misxmoon** [comment]
> Is that a trailing space?

Is that me having sex with your mom? yes, yes it is.

**Comment by FIGBERT** [comment]
get rid of the spaces fucker

**Pull request merged**
